version: '3'
 
#The services section is to define the individual containers (services) that will make up your application.
services:

# ttdsvt application service
  ttdsvtserver:
    image: harinath612/ttdsvt-server
    ports:
      - "8000:8000"

 # ttdsvt application service
  ttdsvtui:
    image: harinath612/ttdsvt-ui
    ports:
      - "3000:3000"
    depends_on:
      - ttdsvtserver
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000/
      - DEBUG_MODE=true

      