version: '3.8'

services:
  database:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ttdsvt
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  web:
    build: .
    command: /ttdsvt/server-env/bin/python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ttdsvt
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  mysql_data:
